[package]
name = "sequencer-monitoring-gen"
# The version of this crate should equal the version of cairo-native.
version = "0.1.0"
edition = "2021"
repository = "https://github.com/starkware-libs/sequencer/"
license = "Apache-2.0"

[dependencies]
clap = "4.5.4"
file = "1.1.2"
serde_json = "1.0.116"
