[package]
name = "apollo_l1_endpoint_monitor"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
apollo_infra.workspace = true
apollo_l1_endpoint_monitor_types.workspace = true
async-trait.workspace = true
tracing.workspace = true
url.workspace = true

[dev-dependencies]

[lints]
workspace = true
