[package]
name = "apollo_l1_gas_price"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
apollo_base_layer.workspace = true
apollo_config.workspace = true
apollo_l1_gas_price_types.workspace = true
apollo_sequencer_infra.workspace = true
async-trait.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
starknet_api.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true
validator.workspace = true

[dev-dependencies]
apollo_base_layer = { workspace = true, features = ["testing"] }
apollo_l1_gas_price_types = { workspace = true, features = ["testing"] }
mockall.workspace = true
mockito.workspace = true

[lints]
workspace = true
