[package]
name = "apollo_l1_gas_price_types"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
apollo_base_layer.workspace = true
apollo_proc_macros.workspace = true
apollo_sequencer_infra.workspace = true
async-trait.workspace = true
mockall.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
starknet_api.workspace = true
strum_macros.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
apollo_base_layer = { workspace = true, features = ["testing"] }
mockall.workspace = true

[lints]
workspace = true

[features]
testing = []
