[package]
name = "infra_utils"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Infrastructure utility."

[lints]
workspace = true

[dependencies]
papyrus_proc_macros.workspace = true
tokio = { workspace = true, features = ["process"] }

[dev-dependencies]
rstest.workspace = true
