[package]
name = "starknet_batcher"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
blockifier.workspace = true
chrono.workspace = true
indexmap.workspace = true
papyrus_config.workspace = true
papyrus_state_reader.workspace = true
papyrus_storage.workspace = true
serde.workspace = true
starknet_api.workspace = true
starknet_batcher_types.workspace = true
starknet_l1_provider_types.workspace = true
starknet_mempool_types.workspace = true
starknet_sequencer_infra.workspace = true
starknet_sequencer_metrics.workspace = true
starknet_state_sync_types.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
validator.workspace = true

[dev-dependencies]
assert_matches.workspace = true
chrono = { workspace = true }
futures.workspace = true
<<<<<<< HEAD
mempool_test_utils.workspace = true
metrics.workspace = true
metrics-exporter-prometheus.workspace = true
||||||| e779088d2
mempool_test_utils.workspace = true
=======
mempool_test_utils.path = "../mempool_test_utils"
>>>>>>> origin/main-v0.13.4
mockall.workspace = true
rstest.workspace = true
starknet-types-core.workspace = true
<<<<<<< HEAD
starknet_api = { workspace = true, features = ["testing"] }
starknet_infra_utils.workspace = true
starknet_l1_provider_types = { workspace = true, features = ["testing"] }
starknet_mempool_types = { workspace = true, features = ["testing"] }
starknet_sequencer_metrics.workspace = true
||||||| e779088d2
starknet_api = { workspace = true, features = ["testing"] }
starknet_l1_provider_types = { workspace = true, features = ["testing"] }
starknet_mempool_types = { workspace = true, features = ["testing"] }
=======
starknet_api = { path = "../starknet_api", features = ["testing"] }
starknet_l1_provider_types = { path = "../starknet_l1_provider_types", features = ["testing"] }
starknet_mempool_types = { path = "../starknet_mempool_types", features = ["testing"] }
>>>>>>> origin/main-v0.13.4
