[package]
name = "starknet_os_proc_macros"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.78"
quote = "1.0.35"
syn = "2.0.48"
