name: Blockifier-Post-Merge

on:
  pull_request:
    types:
      - closed
    paths:
      - '.github/workflows/blockifier_post-merge.yml'
      - 'crates/blockifier/**'
      - 'crates/native_blockifier/**'
      - 'scripts/dependencies.sh'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    container: us-central1-docker.pkg.dev/starkware-thirdparties/sequencer/ci-image:ubuntu-22-04-toolchain-1-83
    runs-on: starkware-ubuntu-20-04-medium
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/bootstrap

      - run: |
          pip install -r crates/blockifier_test_utils/tests/requirements.txt
          cargo test -p blockifier -p native_blockifier -- --include-ignored
