name: Main-CI-Nightly
on:
  schedule:
    - cron: "0 0 * * *" # Runs at 00:00 UTC every day
  workflow_dispatch:

env:
  RUSTFLAGS: "-D warnings -C link-arg=-fuse-ld=lld"

jobs:
  codecov:
    container: us-central1-docker.pkg.dev/starkware-thirdparties/sequencer/ci-image:ubuntu-22-04-toolchain-1-83
    runs-on: starkware-ubuntu-latest-large
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/bootstrap
      - run: npm install -g ganache@7.4.3
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: "Run codecov"
        run: cargo llvm-cov --codecov --output-path codecov.json
        env:
          SEED: 0

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  feature_combos:
    container: us-central1-docker.pkg.dev/starkware-thirdparties/sequencer/ci-image:ubuntu-22-04-toolchain-1-83
    runs-on: starkware-ubuntu-latest-large
    steps:
      - uses: actions/checkout@v4

      # Install rust components.
      - uses: ./.github/actions/bootstrap

      - name: Setup Python venv
        run: |
          python3 -m venv ci
          ci/bin/pip install -r scripts/requirements.txt

      # Run feature combo test.
      - name: "Run feature combo on all crates."
        run: ci/bin/python scripts/run_feature_combos_test.py
