name: Test-All

on:
  push:

env:
  RUSTFLAGS: "-D warnings -C link-arg=-fuse-ld=lld"

jobs:
  test-all:
    runs-on: starkware-ubuntu-latest-medium
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/bootstrap
      - run: npm install -g ganache@7.4.3
      - run: pwd
      - run: ls
      - run: echo $CARGO_HOME
      - run: echo $CARGO_TARGET_DIR
      - run: cargo metadata --format-version 1 | jq .workspace_root
      - run: cargo metadata --format-version 1 | jq -r .target_directory
      - name: Cargo build
        run: cargo build --verbose

      - name: Cargo test # Takes 11 minutes to compile when it's first!!!
        run: cargo test
