[package]
name = "sizeof_macro"
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
quote.workspace = true
syn = { workspace = true, features = ["full"] }
<<<<<<< HEAD
proc-macro2 = "1.0"
=======
proc-macro2 = "1.0"
>>>>>>> 67e733244 (starknet_api: internal implementation of sizeof)
